### ISSUE TITLE
Add a description for the game 

### ISSUE THREAD

**Issue by zurda** [zurda/hangman-react#16]
### Purpose 

Improve UX by adding some description/s about the game and how to play. 

### The problem

This is the page you currently get when opening the game for the first time: 

<img width="500" alt="Screenshot 2020-10-11 at 14 40 52" src="https://user-images.githubusercontent.com/16784959/95680217-d4b99500-0bcf-11eb-843b-582136e2098a.png">

This might be self explanatory, but I would love it if we could add a little guidance to the user. Maybe things like how to play the game, and/or where the data is coming from, how many tries do you get, what does "Hint" do, etc. 

### Suggested solutions 

This can be resolved in any number of ways, and I'll leave it up to whoever picks it up. 

Some solutions might be adding a description paragraph before the game starts, a 'Help' tab with some details about the game, and/or `i` icons around the ui that show explanations on hover. 

Whoever picks this up can really approach this how they like, but at a minimum - a paragraph with instructions on how to play the game should be enough.

**Comment by sofiacarballo** [comment]
Hi! I'd like to help in this issue :)

**Comment by zurda** [comment]
Hi @sofiacarballo , thanks for offering to help! 
I'm assigning you to this issue. Let me know if you need help with anything! 

Just a small heads up: the styling is about to change a bit ([see figma for new design](https://www.figma.com/file/1XIUSqSbv7BKUQIQzUkQRH/Untitled?node-id=0%3A1)), but I don't think it should affect this ticket because the layout should stay roughly the same. I hope this makes sense
