### ISSUE TITLE
Improve styling 

### ISSUE THREAD

**Issue by zurda** [zurda/hangman-react#18]
### Purpose 

Improve how the game looks. 

This is how the game currently look: 

![hangman](https://user-images.githubusercontent.com/16784959/95680466-f451bd00-0bd1-11eb-884c-b16662e18be1.gif)

There are a lot of ways to improve this, and it's really up to whoever takes this to make these decisions. 

I'm happy to add a list of things that could be improved (e.g color theme, letters layout), but any change for the better would be greatly appreciated

**Comment by thadeucity** [comment]
@zurda I can help you with that, can I use Styled Components?

**Comment by zurda** [comment]
Hi @thadeucity , thanks for offering to help. 
You're free to use styled components (just a heads up: the project currently uses Emotion, but feel free to change that).

**Comment by thadeucity** [comment]
Thank you Zurda,

I'm halfway done with the code.

Here is the preview if you want any changes please let me know
https://www.figma.com/file/1XIUSqSbv7BKUQIQzUkQRH/Untitled?node-id=0%3A1

**Comment by zurda** [comment]
Thanks Victor, this looks amazing! Thanks you so much 💜 No changes requested, it's really up to you. As far as I'm concerned this definitely completes the task of improving styling. 

I have a tiny query though, if that's OK: I was planning to [a description about how to play the game](https://github.com/zurda/hangman-react/issues/16). 
A. do you think this kind of description is needed or is the layout self explanatory?
B. If it is needed, can you let me know where you'd put this kind of description? I thought of an info icon with on hover text, or a description that's always there, etc? 

Just looking for a UX opinion. Also, if you can think of other interesting suggestions for this project please feel free to open an issue, or let me know here.

**Comment by zurda** [comment]
Thanks Victor, this looks amazing! Thanks you so much 💜 No changes requested, it's really up to you. As far as I'm concerned this definitely completes the task of improving styling.

**Comment by zurda** [comment]
Thanks again for contributing @thadeucity ! This looks a lot better than I would have hoped :)
