### ISSUE TITLE
Save movies in local storage 

### ISSUE THREAD

**Issue by zurda** [zurda/hangman-react#19]
### Purpose 

We currently don't save the user's previous attempts anywhere. This means that a user can get the same move more than once. 

As a short term solution, we should: 
- Save the user's previous attempts in local storage, and 
- Prevent the user from getting the same movie a second time

**Comment by thadeucity** [comment]
I can handle that, do you prefere that I use context or keep this logic inside the JSX file?

**Comment by zurda** [comment]
Thanks for offering to help with this @thadeucity  
Hmm good question. I can't say I have a preference as I haven't implemented anything of this kind in the past. 
Whichever you think is more readable and easier to maintain is fine by me :)

**Comment by zurda** [comment]
Looks great @thadeucity , thanks for contributing
