### ISSUE TITLE
Improve mobile display 

### ISSUE THREAD

**Issue by zurda** [zurda/hangman-react#25]
# Purpose 

These next two display issues make the game harder to play on mobile: 

(1) allow for movie title to wrap when it's too long for the container 
(2) display poster and description below one another on mobile (rather than next to each other, which looks good on desktop)

(1)
<img width="376" alt="Screenshot 2020-10-14 at 01 17 23" src="https://user-images.githubusercontent.com/16784959/95929285-8a950700-0dbb-11eb-9512-42cfbd35a639.png">

(2)
<img width="375" alt="Screenshot 2020-10-14 at 01 17 54" src="https://user-images.githubusercontent.com/16784959/95929269-7cdf8180-0dbb-11eb-97c4-bfbe93b45119.png">

**Comment by thadeucity** [comment]
Can I work on that?

**Comment by zurda** [comment]
Of course, @thadeucity , go ahead, thanks for offering to help!

**Comment by zurda** [comment]
Looking a lot nicer on mobile, thanks @thadeucity ! 🙌
