### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by thadeucity** [zurda/hangman-react#33]
As every single web interface today this one also deserves a dark theme.

If you want, I can implemente that too.

**Comment by zurda** [comment]
Hi @thadeucity , that's an excellent idea. And I appreciate the offer to work on this, thanks

**Comment by zurda** [comment]
Beautifully done, thanks again @thadeucity ! 

![hangman-react-screen](https://user-images.githubusercontent.com/16784959/97081804-c1a9ba80-15fc-11eb-8907-9d2be088d3d3.png)
