### ISSUE TITLE
Change remaining guesses indication to something cinematic 

### ISSUE THREAD

**Issue by zurda** [zurda/hangman-react#36]
## Purpose 

Right now, the remaining guesses are indicated by hearts: 

<img width="347" alt="Screenshot 2020-10-23 at 21 09 40" src="https://user-images.githubusercontent.com/16784959/97050437-3fc27e80-1575-11eb-8f33-85f605e42c48.png">

To make the game more like hangman, we would like the guesses indicator to be a drawing of something cinematic. For example, a clapper board, a director's chair. The idea is to have the drawing reveal itself using css/ svg. 

As you make your guesses, lines are added to the guesses section to draw something. Here are a few drawings for inspiration. Any other ideas are welcome

<img width="145" alt="Screenshot 2020-10-23 at 21 13 27" src="https://user-images.githubusercontent.com/16784959/97050606-9465f980-1575-11eb-9484-2623a3ab7def.png">

<img width="214" alt="Screenshot 2020-10-23 at 21 20 46" src="https://user-images.githubusercontent.com/16784959/97050679-b8c1d600-1575-11eb-8d0b-5a705504551c.png">

<img width="171" alt="Screenshot 2020-10-23 at 21 21 18" src="https://user-images.githubusercontent.com/16784959/97050684-bb243000-1575-11eb-83af-22c3723f2417.png">

**Comment by thadeucity** [comment]
I can easily change to one of the following: 
https://fontawesome.com/icons/film?style=solid
https://fontawesome.com/icons/video?style=solid
https://feathericons.com/?query=video

I believe they match really well with the Material Design theme used for the rest of the application

**Comment by zurda** [comment]
They're really nice. Feel free to change them if you think it adds some fun to the app Thanks!

**Comment by zurda** [comment]
Thanks @thadeucity ,I appreciate your help :)
